// <auto-generated />
using System;
using Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infraestructure.DataModel.EFAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("WorkShopId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5809ee5-491f-49c1-90fd-54b352143507"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 118, DateTimeKind.Utc).AddTicks(4846),
                            Email = "email@gmail.com",
                            FailedAttempts = 0,
                            IsLocked = false,
                            Password = "$2a$11$C5/4RLeiYsVJn6VjOVum3uu6n9SPUkHe4IthJiY9r7htr3Pkgm36O",
                            WorkShopId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("b764d3d2-3790-4448-9e18-43dbb000047d"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 349, DateTimeKind.Utc).AddTicks(2636),
                            Email = "email2@gmail.com",
                            FailedAttempts = 0,
                            IsLocked = false,
                            Password = "$2a$11$8wuF5A.wQguNh0AB4c/Qn.vT/rGdmIRYC4oNUSIb8ZoyUtLq9xmMa",
                            WorkShopId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string[]>("Email")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkShopId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 578, DateTimeKind.Utc).AddTicks(3599),
                            Email = new[] { "lucaspirez42@gmail.com" },
                            FirstName = "Juan ",
                            LastName = "Perez",
                            PhoneNumber = new[] { "3424388239" },
                            WorkShopId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 578, DateTimeKind.Utc).AddTicks(3640),
                            Email = new string[0],
                            FirstName = "Maria ",
                            LastName = "Lopez",
                            PhoneNumber = new string[0],
                            WorkShopId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFRepairOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FinalAmount")
                        .HasColumnType("double precision");

                    b.Property<bool>("NotifycationSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WorkShopId");

                    b.ToTable("VehicleEntries");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFWorkShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkShops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 118, DateTimeKind.Utc).AddTicks(4698),
                            Name = "Taller Jesus"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 8, 5, 17, 26, 11, 118, DateTimeKind.Utc).AddTicks(4725),
                            Name = "Taller Silvana"
                        });
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFAdmin", b =>
                {
                    b.HasOne("Infraestructure.DataModel.EFWorkShop", "WorkShop")
                        .WithMany()
                        .HasForeignKey("WorkShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShop");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFCustomer", b =>
                {
                    b.HasOne("Infraestructure.DataModel.EFWorkShop", "WorkShop")
                        .WithMany("Customers")
                        .HasForeignKey("WorkShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShop");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFRepairOrder", b =>
                {
                    b.HasOne("Infraestructure.DataModel.EFVehicle", "Vehicle")
                        .WithMany("VehicleEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infraestructure.DataModel.EFWorkShop", "WorkShop")
                        .WithMany("VehicleEntries")
                        .HasForeignKey("WorkShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Infraestructure.DataModel.EFSparePart", "SpareParts", b1 =>
                        {
                            b1.Property<Guid>("EFRepairOrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("Price")
                                .HasColumnType("double precision");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("EFRepairOrderId", "Id");

                            b1.ToTable("EFSparePart");

                            b1.WithOwner()
                                .HasForeignKey("EFRepairOrderId");
                        });

                    b.Navigation("SpareParts");

                    b.Navigation("Vehicle");

                    b.Navigation("WorkShop");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFVehicle", b =>
                {
                    b.HasOne("Infraestructure.DataModel.EFCustomer", "Customer")
                        .WithMany("Vehicle")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFCustomer", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFVehicle", b =>
                {
                    b.Navigation("VehicleEntries");
                });

            modelBuilder.Entity("Infraestructure.DataModel.EFWorkShop", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("VehicleEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
